# Generated by Django 3.2.6 on 2021-08-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210819_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='dateposted',
        ),
    ]
